name: amplimap
channels:
- bioconda
- conda-forge
dependencies:
- bcftools>=1.5
- bedtools=2.27.*
- bowtie2=2.3.*
- bwa=0.7.*
- gatk4=4.0.*
- picard=2.18.*
- samtools>=1.5
- star=2.5.*
- python=3.6.*
- pip
- setuptools>=18.0
- cython
- numpy
- pip:
  - amplimap