align:
  aligner: naive
  bowtie2:
    report_n: 1
annotate:
  annovar:
    operations: g,f,f,f,f,f,f,f,f,f,f
    protocols: refGene,esp6500siv2_all,1000g2014oct_all,avsnp147,cosmic82,dbnsfp33a,clinvar_20150629,dbscsnv11,exac03,gnomad_genome,gnomad_exome
  include_exon_distance: false
  include_gbrowse_links: false
  include_score: false
clusters:
  bsub:
    command_nosync: bsub -oo {workflow.workdir_init}/cluster_log/%J.log
  qsub:
    command_sync: qsub -o {workflow.workdir_init}/cluster_log/ -sync yes -j y -m n
general:
  amplimap_parent_dir: /mnt/c/Users/koell/projects/amplimap
  genome_name: ecoli
  ignore_umis: true
  lanes: 0
  mask_bed: ''
  umi_min_consensus_count: 1
  umi_min_consensus_percentage: 51
  umi_tag_name: ''
  use_raw_reads: false
modules:
  annovar: ''
  bcftools: ''
  bedtools: ''
  bowtie2: ''
  bwa: ''
  gatk: ''
  picard: ''
  platypus: ''
  samtools: ''
  star: ''
parse_reads:
  max_mismatches: 2
  min_percentage_good: 0
  quality_trim_phred_base: 33
  quality_trim_threshold: false
  trim_min_length: 20
  trim_primers: true
  umi_one: 0
  umi_two: 0
paths:
  ecoli:
    bowtie2: ../ecoli.fasta
    bwa: ../ecoli.fasta
    fasta: ../ecoli.fasta
  hg38:
    annovar: ''
    annovar_name: ''
    bowtie2: ''
    bwa: ''
    fasta: ''
    star: ''
  mm10:
    bwa: ''
pileup:
  filter_softclipped: false
  group_with_mate_positions: false
  min_baseq: 30
  min_mapq: 0
  subsample_reads: false
  validate_probe_targets: false
variants:
  caller: platypus
  caller_low_frequency: mutect2
  gatk:
    parameters: --disable-read-filter MappingQualityAvailableReadFilter --disable-read-filter
      WellformedReadFilter
  mutect2:
    parameters: ''
  platypus:
    parameters: --filterDuplicates=0 --filterReadsWithDistantMates=0 --minFlank=0
      --trimOverlapping=0 --sbThreshold=0 --abThreshold=0
